---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-np
  labels:
    app: nginx
    purpose: svcdemo
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - targetPort: 80
      port: 80
      nodePort: 32024